import type { Dashboard } from "./schemas";
import type { Backup } from "./schemas";
const now = Date.now();
export const demoBackups: Backup[] = [
  {
    id: "demo-backup-supabase",
    databaseId: "supabase-db",
    databaseName: "Supabase PostgreSQL",
    engine: "PostgreSQL 17",
    frequency: "daily",
    enabled: true,
    saveS3: false,
    s3StorageId: "",
    executions: [
      {
        id: "demo-execution-today",
        filename: "supabase-2026-10-05.sql.gz",
        size: 8600000000,
        date: new Date(now - 2 * 3600000).toISOString(),
        status: "success",
        message: "",
      },
    ],
  },
];
export const demoData: Dashboard = {
  demo: true,
  connected: false,
  coolifyUrl: "",
  warnings: [],
  resources: [
    {
      id: "planner",
      name: "Planner API",
      kind: "app",
      status: "running",
      domain: "https://api.planner.example.com",
      description: "Your days, a little more organized.",
      branch: "main",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "trekking",
      name: "Trekking Website",
      kind: "app",
      status: "running",
      domain: "https://trekkingbootsnepal.com",
      description: "A home for the next adventure.",
      branch: "main",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "immich",
      name: "Immich",
      kind: "app",
      status: "running",
      domain: "https://photos.example.com",
      description: "All your memories, in one place.",
      branch: "main",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "paperless",
      name: "Paperless",
      kind: "app",
      status: "running",
      domain: "https://docs.example.com",
      description: "A little less paper. A little more order.",
      branch: "main",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "homepage",
      name: "Personal website",
      kind: "app",
      status: "stopped",
      domain: "https://home.example.com",
      description: "Your small corner of the internet.",
      branch: "main",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "supabase-db",
      name: "Supabase PostgreSQL",
      kind: "database",
      status: "running",
      domain: "",
      description: "PostgreSQL 17",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "n8n-db",
      name: "n8n PostgreSQL",
      kind: "database",
      status: "running",
      domain: "",
      description: "PostgreSQL 16",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "redis",
      name: "Redis",
      kind: "database",
      status: "running",
      domain: "",
      description: "Redis 7",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [],
    },
    {
      id: "n8n",
      name: "n8n",
      kind: "service",
      status: "running",
      domain: "https://automation.example.com",
      description: "Your everyday tasks, on autopilot.",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [
        {
          id: "n8n-application",
          kind: "application",
          name: "n8n",
          status: "running",
        },
        {
          id: "n8n-database",
          kind: "database",
          name: "PostgreSQL",
          status: "running",
        },
      ],
    },
    {
      id: "supabase",
      name: "Supabase",
      kind: "service",
      status: "running",
      domain: "https://supabase.example.com",
      description: "Database, auth, and storage.",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [
        {
          id: "supabase-postgres",
          kind: "database",
          name: "Postgres",
          status: "running",
        },
        {
          id: "supabase-auth",
          kind: "application",
          name: "Auth",
          status: "running",
        },
        {
          id: "supabase-storage",
          kind: "application",
          name: "Storage",
          status: "running",
        },
        {
          id: "supabase-realtime",
          kind: "application",
          name: "Realtime",
          status: "running",
        },
        {
          id: "supabase-rest",
          kind: "application",
          name: "REST API",
          status: "running",
        },
      ],
    },
    {
      id: "tunnel",
      name: "Cloudflare Tunnel",
      kind: "service",
      status: "running",
      domain: "",
      description: "A secure way home.",
      branch: "",
      environment: "Production",
      environmentId: "production",
      projectId: "homelab",
      projectName: "Homelab",
      coolifyUrl: "",
      components: [
        {
          id: "tunnel-app",
          kind: "application",
          name: "Tunnel",
          status: "running",
        },
      ],
    },
  ],
  deployments: [
    {
      id: "d1",
      resourceId: "planner",
      name: "Planner API",
      status: "successful",
      branch: "main",
      commit: "a83d923",
      message: "feat: improve itinerary planner",
      date: new Date(now - 5 * 60000).toISOString(),
      duration: "48s",
      logs: "Repository pulled\nImage built\nContainer started\nHealth check passed",
    },
    {
      id: "d2",
      resourceId: "trekking",
      name: "Trekking Website",
      status: "successful",
      branch: "main",
      commit: "e7c19a2",
      message: "Update trail guides",
      date: new Date(now - 2 * 3600000).toISOString(),
      duration: "1m 12s",
      logs: "Deployment completed successfully",
    },
    {
      id: "d3",
      resourceId: "planner",
      name: "Planner API",
      status: "failed",
      branch: "main",
      commit: "b191c21",
      message: "fix: update dependencies",
      date: new Date(now - 24 * 3600000).toISOString(),
      duration: "32s",
      logs: "Installing dependencies\nBuild exited with code 1\nError: missing environment variable DATABASE_URL",
    },
    {
      id: "d4",
      resourceId: "immich",
      name: "Immich",
      status: "successful",
      branch: "main",
      commit: "f92ac13",
      message: "Update to latest release",
      date: new Date(now - 27 * 3600000).toISOString(),
      duration: "56s",
      logs: "Deployment completed successfully",
    },
  ],
  servers: [
    {
      id: "home",
      name: "Home Server",
      online: true,
      ip: "192.168.1.100",
      os: "Ubuntu 24.04 LTS",
      cpu: 21,
      memory: 6.4,
      memoryTotal: 16,
      storage: 183,
      storageTotal: 512,
    },
  ],
};
export function isDemo() {
  return (
    process.env.HOMEBASE_DEMO === "true" ||
    (process.env.NODE_ENV !== "production" &&
      process.env.HOMEBASE_DEMO !== "false" &&
      !process.env.HOMEBASE_PASSWORD_HASH &&
      !process.env.COOLIFY_TOKEN &&
      !process.env.HOMEBASE_COOLIFY_TOKEN)
  );
}
