// One-click service templates from coollabsio/coolify templates/service-templates.json.
// Availability depends on the installed Coolify version. Types not listed can still be entered.
export const serviceTemplates: [
  slug: string,
  slogan: string,
  category: string,
][] = [
  [
    "9router",
    "Free AI coding gateway. Routes Claude Code, Codex, Cursor, Cline, Copilot requests to 4…",
    "ai",
  ],
  ["activepieces", "Open source no-code business automation.", "automation"],
  ["actualbudget", "A local-first personal finance app.", "finance"],
  [
    "affine",
    "Affine is an open-source, all-in-one workspace and OS for knowledge management, a Notio…",
    "productivity",
  ],
  [
    "alexandrie",
    "A powerful Markdown workspace designed for speed, clarity, and creativity.",
    "productivity",
  ],
  [
    "anythingllm",
    "AnythingLLM is the easiest to use, all-in-one AI application that can do RAG, AI Agents…",
    "ai",
  ],
  [
    "appflowy",
    "AppFlowy is the AI collaborative workspace where you achieve more without losing contro…",
    "productivity",
  ],
  ["apprise-api", "Push Notifications API", "automation"],
  [
    "appsmith",
    "A low-code application platform for building internal tools.",
    "productivity",
  ],
  [
    "appwrite",
    "A backend-as-a-service platform that simplifies the web & mobile app development.",
    "backend",
  ],
  [
    "argilla",
    "Argilla is a collaboration tool for AI engineers and domain experts who need to build h…",
    "ai",
  ],
  [
    "audiobookshelf",
    "Self-hosted audiobook, ebook, and podcast server",
    "media",
  ],
  [
    "authentik",
    "An open-source Identity Provider, focused on flexibility and versatility.",
    "auth",
  ],
  [
    "autobase",
    "Autobase for PostgreSQL® is an open-source alternative to cloud-managed databases (self…",
    "database",
  ],
  [
    "babybuddy",
    "It helps parents track their baby's daily activities, growth, and health with ease.",
    "productivity",
  ],
  [
    "bento-pdf",
    "Process PDFs entirely in your browser. No uploads. No servers. Complete privacy.",
    "productivity",
  ],
  [
    "beszel",
    "A lightweight server resource monitoring hub with historical data, docker stats, and al…",
    "monitoring",
  ],
  ["beszel-agent", "Monitoring agent for Beszel", "monitoring"],
  ["bitcoin-core", "A self-hosted Bitcoin Core full node.", "backend"],
  ["bluesky-pds", "Bluesky PDS (Personal Data Server)", "backend"],
  [
    "bookstack",
    "BookStack is a simple, self-hosted, easy-to-use platform for organising and storing inf…",
    "cms",
  ],
  ["browserless", "A headless Chrome browser as a service.", "devtools"],
  ["budge", "A budgeting personal finance app.", "finance"],
  [
    "budibase",
    "Low code platform for building business apps and workflows in minutes. Supports Postgre…",
    "automation",
  ],
  ["bugsink", "Self-hosted Error Tracking.", "monitoring"],
  ["bulwark", "Modern webmail platform", "Mail"],
  [
    "buzz",
    "Self-hostable workspace where humans and AI agents collaborate on a Nostr relay you own.",
    "messaging",
  ],
  [
    "calibre-web",
    "Calibre-web is a web app providing a clean interface for browsing, reading and download…",
    "media",
  ],
  [
    "calibre-web-automated-book-downloader",
    "An intuitive web interface for searching and requesting book downloads, designed to wor…",
    "media",
  ],
  [
    "cap",
    "Cap is the open source alternative to Loom. Lightweight, powerful, and cross-platform.…",
    "media",
  ],
  ["cap-captcha", "The self-hosted CAPTCHA for the modern web.", "security"],
  [
    "castopod",
    "Castopod is a free & open-source hosting platform made for podcasters who want engage a…",
    "media",
  ],
  [
    "celld",
    "Self-hosted, distributed Durable Objects powered by Deno.",
    "backend",
  ],
  [
    "changedetection",
    "Website change detection monitor and notifications.",
    "monitoring",
  ],
  [
    "chaskiq",
    "Chaskiq is an messaging platform for marketing, support & sales",
    "helpdesk",
  ],
  ["chatwoot", "Delightful customer relationships at scale.", "helpdesk"],
  [
    "checkmate",
    "An open source server and websites monitoring application",
    "monitoring",
  ],
  [
    "chibisafe",
    "A beautiful and performant vault to save all your files in the cloud.",
    "storage",
  ],
  [
    "chroma",
    "Chroma is the open-source search and retrieval database for AI applications.",
    "ai",
  ],
  [
    "classicpress-with-mariadb",
    "A lightweight, stable, instantly familiar free open-source content management system, b…",
    "cms",
  ],
  [
    "classicpress-with-mysql",
    "A lightweight, stable, instantly familiar free open-source content management system, b…",
    "cms",
  ],
  [
    "classicpress-without-database",
    "A lightweight, stable, instantly familiar free open-source content management system, b…",
    "cms",
  ],
  [
    "cloudbeaver",
    "CloudBeaver is a lightweight web application designed for comprehensive data management.",
    "devtools",
  ],
  [
    "cloudflare-ddns",
    "A small, feature-rich, and robust Cloudflare DDNS updater.",
    "automation",
  ],
  [
    "cloudflared",
    "Client for Cloudflare Tunnel, a daemon that exposes private services through the Cloudf…",
    "proxy",
  ],
  ["cloudreve", "A self-hosted file management and sharing system.", "storage"],
  [
    "cockpit",
    "Cockpit is a headless content platform that is lightweight, fast and ready for takeoff.",
    "cms",
  ],
  [
    "code-server",
    "Code-Server is a web-based code editor that enables remote coding and collaboration fro…",
    "devtools",
  ],
  [
    "codimd",
    "Realtime collaborative markdown notes on all platforms",
    "productivity",
  ],
  [
    "convertx",
    "A self-hosted online file converter. Supports over a thousand different formats.",
    "backend",
  ],
  [
    "convex",
    "Convex is the open-source reactive database for app developers.",
    "backend",
  ],
  [
    "cryptgeon",
    "Secure note / file sharing service inspired by PrivNote.",
    "security",
  ],
  [
    "cyberchef",
    "The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data a…",
    "security",
  ],
  [
    "dashy",
    "A self-hostable personal dashboard built for you. Includes status-checking, widgets, th…",
    "productivity",
  ],
  [
    "databasus",
    "Databasus is a free, open source and self-hosted tool to backup PostgreSQL, MySQL, and…",
    "devtools",
  ],
  ["deno-kv", "The Denoland key-value database", "database"],
  [
    "directus",
    "Directus wraps databases with a dynamic API, and provides an intuitive app for managing…",
    "cms",
  ],
  [
    "directus-with-postgresql",
    "Directus wraps databases with a dynamic API, and provides an intuitive app for managing…",
    "cms",
  ],
  [
    "diun",
    "Docker Image Update Notifier is a CLI application to receive notifications when a Docke…",
    "automation",
  ],
  [
    "docker-registry",
    "The Docker Registry lets you distribute Docker images.",
    "devtools",
  ],
  [
    "docling",
    "Convert documents (PDF, DOCX, PPTX, images, HTML) to Markdown, JSON, and more using AI-…",
    "ai",
  ],
  [
    "docmost",
    "Open-source collaborative wiki and documentation software",
    "productivity",
  ],
  ["documenso", "Document signing, finally open source", "productivity"],
  [
    "docuseal",
    "Document Signing for Everyone free forever for individuals, extensible for businesses a…",
    "productivity",
  ],
  [
    "docuseal-with-postgres",
    "Document Signing for Everyone free forever for individuals, extensible for businesses a…",
    "productivity",
  ],
  [
    "dokuwiki",
    "A lightweight and easy-to-use wiki platform for creating and managing documentation and…",
    "cms",
  ],
  [
    "dolibarr",
    "Dolibarr is a modern software package to manage your organization's activity (contacts,…",
    "productivity",
  ],
  [
    "dozzle",
    "Dozzle is a simple and lightweight web UI for Docker logs.",
    "devtools",
  ],
  [
    "dozzle-with-auth",
    "Dozzle is a simple and lightweight web UI for Docker logs.",
    "devtools",
  ],
  [
    "drizzle-gateway",
    "Free self-hosted Drizzle Studio on steroids",
    "devtools",
  ],
  [
    "drupal-with-postgresql",
    "Drupal is a free and open-source web content management system written in PHP and distr…",
    "cms",
  ],
  [
    "duplicati",
    "Duplicati is a backup solution, allowing you to make scheduled backups with encryption.",
    "storage",
  ],
  [
    "easyappointments",
    "Schedule Anything. Let's start with easy! Get the best free online appointment schedule…",
    "productivity",
  ],
  [
    "elasticsearch",
    "Elasticsearch is free and Open Source, Distributed, RESTful Search Engine.",
    "search",
  ],
  [
    "elasticsearch-with-kibana",
    "Elastic + Kibana is a Free and Open Source Search, Monitoring, and Visualization Stack",
    "monitoring",
  ],
  [
    "electricsql",
    "Sync shape-based subsets of your Postgres data over HTTP.",
    "backend",
  ],
  [
    "emby",
    "A media server software that allows you to organize, stream, and access your multimedia…",
    "media",
  ],
  [
    "embystat",
    "EmbyStat is a web analytics tool, designed to provide insight into website traffic and…",
    "analytics",
  ],
  [
    "emqx-enterprise",
    "Open-source MQTT broker for IoT, IIoT, and connected vehicles.",
    "Networking",
  ],
  ["engram", "Persistent memory sync server for AI coding agents (MCP).", "ai"],
  [
    "ente-photos",
    "Ente Photos is a fully open source, End to End Encrypted alternative to Google Photos a…",
    "media",
  ],
  [
    "ente-photos-with-s3",
    "Ente Photos is a fully open source, End to End Encrypted alternative to Google Photos a…",
    "media",
  ],
  ["esphome", "Smart Home Made Simple.", "automation"],
  [
    "espocrm",
    "EspoCRM is a free and open-source CRM platform.",
    "productivity",
  ],
  [
    "evolution-api",
    "Multi-platform messaging (whatsapp and more) integration API",
    "backend",
  ],
  [
    "excalidraw",
    "Virtual whiteboard for sketching hand-drawn like diagrams",
    "productivity",
  ],
  [
    "executor",
    "Self-hosted AI agent integrations and code execution server.",
    "development",
  ],
  [
    "faraday",
    "Faraday is a powerful, open-source, web-based vulnerability management tool.",
    "security",
  ],
  [
    "fider",
    "Fider is a feedback platform for collecting and managing user feedback.",
    "productivity",
  ],
  [
    "filebrowser",
    "FileBrowser is a web-based file manager and file explorer with a user-friendly interface.",
    "storage",
  ],
  [
    "fileflows",
    "FileFlows can drastically reduce your files, up to 90%, saving you space and money. No…",
    "media",
  ],
  [
    "firefly",
    "A personal finances manager that can help you save money.",
    "finance",
  ],
  [
    "firefox",
    "Fast, private, and self-hosted secure browser for browsing without limits.",
    "productivity",
  ],
  [
    "fizzy",
    "Kanban tracking tool for issues and ideas by 37signals",
    "productivity",
  ],
  [
    "flipt",
    "Flipt is a fully managed feature flag solution that enables you to keep your feature fl…",
    "backend",
  ],
  [
    "flowise",
    "Flowise is an open source low-code tool for developers to build customized LLM orchestr…",
    "ai",
  ],
  [
    "flowise-with-databases",
    "Flowise is an open source low-code tool for developers to build customized LLM orchestr…",
    "ai",
  ],
  [
    "forgejo",
    "Forgejo is a self-hosted lightweight software forge. Easy to install and low maintenanc…",
    "git",
  ],
  [
    "forgejo-with-mariadb",
    "Forgejo is a self-hosted lightweight software forge. Easy to install and low maintenanc…",
    "git",
  ],
  [
    "forgejo-with-mysql",
    "Forgejo is a self-hosted lightweight software forge. Easy to install and low maintenanc…",
    "git",
  ],
  [
    "forgejo-with-postgresql",
    "Forgejo is a self-hosted lightweight software forge. Easy to install and low maintenanc…",
    "git",
  ],
  ["formbricks", "Open Source Survey Platform", "productivity"],
  [
    "foundryvtt",
    "Foundry Virtual Tabletop is a self-hosted & modern roleplaying platform",
    "games",
  ],
  [
    "freescout",
    "FreeScout is the super lightweight and powerful free open source help desk and shared i…",
    "helpdesk",
  ],
  ["freshrss", "A free, self-hostable feed aggregator.", "RSS"],
  ["freshrss-with-mariadb", "A free, self-hostable feed aggregator.", "RSS"],
  ["freshrss-with-mysql", "A free, self-hostable feed aggregator.", "RSS"],
  ["freshrss-with-postgresql", "A free, self-hostable feed aggregator.", "RSS"],
  [
    "garage",
    "Garage is an S3-compatible distributed object storage service designed for self-hosting.",
    "storage",
  ],
  ["getoutline", "Your team’s knowledge base", "productivity"],
  [
    "ghost",
    "Ghost is a content management system (CMS) and blogging platform.",
    "cms",
  ],
  [
    "gitea",
    "Gitea is a self-hosted, lightweight Git service, offering version control, collaboratio…",
    "git",
  ],
  ["gitea-runner", "Gitea Actions runner for docker", "devtools"],
  [
    "gitea-with-mariadb",
    "Gitea is a self-hosted, lightweight Git service, offering version control, collaboratio…",
    "git",
  ],
  [
    "gitea-with-mysql",
    "Gitea is a self-hosted, lightweight Git service, offering version control, collaboratio…",
    "git",
  ],
  [
    "gitea-with-postgresql",
    "Gitea is a self-hosted, lightweight Git service, offering version control, collaboratio…",
    "git",
  ],
  ["github-runner", "A GitHub Actions runner for Docker", "devtools"],
  [
    "gitlab",
    "The all-in-one DevOps platform for seamless collaboration and continuous delivery.",
    "git",
  ],
  [
    "glance",
    "A self-hosted dashboard that puts all your feeds in one place.",
    "productivity",
  ],
  ["glances", "An Eye on your system", "monitoring"],
  ["glitchtip", "GlitchTip is a error tracking system.", "monitoring"],
  [
    "glpi",
    "GLPI (Gestionnaire Libre de Parc Informatique) is a free, open-source IT Service Manage…",
    "helpdesk",
  ],
  ["goatcounter", "Lightweight web analytics platform.", "analytics"],
  [
    "gotenberg",
    "Gotenberg is a Docker-powered stateless API for PDF files.",
    "devtools",
  ],
  [
    "gotify",
    "Gotify is an open-source self-hosted notification server.",
    "messaging",
  ],
  [
    "gowa",
    "Golang WhatsApp - Built with Go for efficient memory use",
    "messaging",
  ],
  [
    "grafana",
    "Grafana is the open source analytics & monitoring solution for every database.",
    "monitoring",
  ],
  [
    "grafana-with-postgresql",
    "Grafana is the open source analytics & monitoring solution for every database.",
    "monitoring",
  ],
  ["gramps-web", "Open Source Online Genealogy System.", "family"],
  [
    "grimmory",
    "Grimmory is a self-hosted application for managing your entire book collection in one p…",
    "other",
  ],
  [
    "grist",
    "Grist is a modern relational spreadsheet. It combines the flexibility of a spreadsheet…",
    "productivity",
  ],
  [
    "grocy",
    "Grocy is a web-based household management and grocery list application.",
    "productivity",
  ],
  [
    "hatchet",
    "Hatchet allows you to run background tasks at scale with a high-throughput, low-latency…",
    "automation",
  ],
  [
    "healthchecks",
    "Healthchecks is a cron job monitoring service. It listens for HTTP requests and email m…",
    "monitoring",
  ],
  [
    "heimdall",
    "Heimdall is a dashboard for managing and organizing your server applications.",
    "productivity",
  ],
  [
    "hermes-agent",
    "Hermes Agent - autonomous AI agent with persistent memory, scheduling, and built-in web…",
    "ai",
  ],
  [
    "hermes-agent-with-webui",
    "Hermes Agent - autonomous AI agent with persistent memory, scheduling, and a self-hoste…",
    "ai",
  ],
  [
    "heyform",
    "Allows anyone to create engaging conversational forms for surveys, questionnaires, quiz…",
    "productivity",
  ],
  [
    "homarr",
    "Homarr is a self-hosted homepage for your services.",
    "productivity",
  ],
  [
    "home-assistant",
    "Open source home automation that puts local control and privacy first.",
    "automation",
  ],
  [
    "homebox",
    "Homebox is the inventory and organization system built for the Home User.",
    "productivity",
  ],
  [
    "homepage",
    "A modern, fully static, fast, secure fully proxied, highly customizable application das…",
    "productivity",
  ],
  [
    "honcho",
    "Honcho is a developer tool to build personalized AI agents with production-ready memory…",
    "ai",
  ],
  ["hoppscotch", "The Open Source API Development Platform", "devtools"],
  [
    "imgcompress",
    "Offline image compression, conversion, and AI background removal for Docker homelabs.",
    "media",
  ],
  ["immich", "Self-hosted photo and video management solution.", "media"],
  [
    "infisical",
    "Infisical is the open source secret management platform that developers use to centrali…",
    "security",
  ],
  [
    "influxdb",
    "Open source time series database for metrics, events, and analytics.",
    "databases",
  ],
  [
    "inngest",
    "Durable workflow engine for background jobs, queues and scheduled tasks.",
    "automation",
  ],
  ["invoice-ninja", "The leading open-source invoicing platform", "finance"],
  [
    "it-tools",
    "IT Tools is a self-hosted solution for managing various IT tasks.",
    "devtools",
  ],
  [
    "jean",
    "Open-source desktop and server client for orchestrating AI coding agents.",
    "development",
  ],
  [
    "jellyfin",
    "Jellyfin is a media server for hosting and streaming your media collection.",
    "media",
  ],
  [
    "jenkins",
    "Jenkins is an open source automation server, Jenkins provides hundreds of plugins to su…",
    "ci",
  ],
  [
    "jitsi",
    "Self-hosted Jitsi Meet — open-source video conferencing platform",
    "productivity",
  ],
  [
    "joomla-with-mariadb",
    "Joomla! is the mobile-ready and user-friendly way to build your website. Choose from th…",
    "cms",
  ],
  ["joplin", "Self-hosted sync server for Joplin", "productivity"],
  [
    "jupyter-notebook-python",
    "Jupyter Notebook is an open-source web application that allows you to create and share…",
    "devtools",
  ],
  [
    "karakeep",
    "A self-hostable bookmark-everything app (links, notes and images) with AI-based automat…",
    "productivity",
  ],
  [
    "keycloak",
    "Keycloak is an open-source Identity and Access Management tool.",
    "auth",
  ],
  [
    "keycloak-with-postgres",
    "Keycloak is an open-source Identity and Access Management tool.",
    "auth",
  ],
  ["kimai", "Open source time-tracking app.", "productivity"],
  [
    "kuzzle",
    "Kuzzle is a generic backend offering the basic building blocks common to every applicat…",
    "backend",
  ],
  [
    "labelstudio",
    "Label Studio is a multi-type data labeling and annotation tool with standardized output…",
    "ai",
  ],
  [
    "langflow",
    "Langflow is an open-source, Python-based, customizable framework for building AI applic…",
    "ai",
  ],
  [
    "langfuse",
    "Langfuse is an open-source LLM engineering platform that helps teams collaboratively de…",
    "ai",
  ],
  [
    "leantime",
    "Leantime is a goals focused project management system for non-project managers.",
    "productivity",
  ],
  [
    "librechat",
    "Self-hosted, powerful, and privacy-focused chat UI for multiple AI models",
    "ai",
  ],
  [
    "libreoffice",
    "LibreOffice is a free and powerful office suite.",
    "productivity",
  ],
  ["librespeed", "Self-hosted lightweight Speed Test.", "devtools"],
  [
    "libretranslate",
    "Free and open-source machine translation API, entirely self-hosted.",
    "ai",
  ],
  [
    "lidarr",
    "Lidarr - a music collection manager for Usenet and BitTorrent users",
    "media",
  ],
  [
    "limesurvey",
    "Simple, quick and anonymous online survey tool that's bursting with juicy insights.",
    "productivity",
  ],
  [
    "linkding",
    "A self-hosted bookmark manager designed to be minimal, fast, and easy to set up.",
    "RSS",
  ],
  [
    "linkding-plus",
    "A self-hosted bookmark manager designed to be minimal, fast, and easy to set up. (Inclu…",
    "RSS",
  ],
  [
    "linkwarden",
    "A self-hostable collaborative bookmark manager to collect, organize, and preserve web p…",
    "productivity",
  ],
  ["listmonk", "Self-hosted newsletter and mailing list manager", "email"],
  [
    "litellm",
    "Call all LLM APIs using the OpenAI format. Use Bedrock, Azure, OpenAI, Cohere, Anthropi…",
    "ai",
  ],
  ["lobe-chat", "An open-source, modern-design AI chat framework.", "ai"],
  [
    "logto",
    "A comprehensive identity solution covering both the front and backend, complete with pr…",
    "auth",
  ],
  [
    "lowcoder",
    "Lowcoder (forked from OpenBlocks) is a self-hosted, open-source, low-code platform for…",
    "productivity",
  ],
  [
    "mage-ai",
    "Build, run, and manage data pipelines for integrating and transforming data.",
    "automation",
  ],
  ["mailpit", "Email & SMTP testing tool with API for developers", "email"],
  [
    "marimo",
    "An open-source reactive notebook for Python — reproducible, git-friendly, SQL built-in,…",
    "devtools",
  ],
  [
    "martin",
    "Martin is a tile server able to generate and serve vector tiles on the fly from large P…",
    "backend",
  ],
  [
    "matrix-synapse-with-postgresql",
    "Chat securely with your family, friends, community, or build great apps with Matrix!",
    "messaging",
  ],
  [
    "matrix-synapse-with-sqlite",
    "Chat securely with your family, friends, community, or build great apps with Matrix!",
    "messaging",
  ],
  [
    "mattermost",
    "Mattermost is an open source, self-hosted Slack-alternative.",
    "messaging",
  ],
  ["mealie", "A recipe manager and meal planner.", "productivity"],
  [
    "mediawiki",
    "MediaWiki is a collaboration and documentation platform brought to you by a vibrant com…",
    "cms",
  ],
  [
    "meilisearch",
    "MeiliSearch is a powerful, fast, easy to use and deploy search engine.",
    "search",
  ],
  [
    "memos",
    "An open-source, lightweight note-taking solution. The pain-less way to create your mean…",
    "productivity",
  ],
  [
    "metabase",
    "Fast analytics with the friendly UX and integrated tooling to let your company explore…",
    "analytics",
  ],
  [
    "metamcp",
    "MCP Aggregator, Orchestrator, Middleware, Gateway in one app",
    "mcp",
  ],
  [
    "metube",
    "A web GUI for youtube-dl with playlist support. It enables you to effortlessly download…",
    "media",
  ],
  [
    "mindsdb",
    "MindsDB is the platform for building AI from enterprise data, enabling smarter organiza…",
    "ai",
  ],
  [
    "minecraft",
    "Minecraft Server that will automatically download selected version at startup.",
    "games",
  ],
  ["miniflux", "Miniflux is a minimalist and opinionated feed reader.", "RSS"],
  [
    "mixpost",
    "Mixpost is a robust and versatile social media management software, designed to streaml…",
    "analytics",
  ],
  [
    "moodle",
    "Moodle is the world’s most customisable and trusted eLearning solution that empowers ed…",
    "cms",
  ],
  [
    "mosquitto",
    "Mosquitto is lightweight and suitable for use on all devices, from low-power single-boa…",
    "messaging",
  ],
  ["n8n", "n8n is an extendable workflow automation tool.", "automation"],
  [
    "n8n-with-postgres-and-worker",
    "n8n is an extendable workflow automation tool with queue mode and workers.",
    "automation",
  ],
  [
    "n8n-with-postgresql",
    "n8n is an extendable workflow automation tool.",
    "automation",
  ],
  [
    "navidrome",
    "Standalone server, that allows you to browse and listen to your music collection using…",
    "media",
  ],
  [
    "neon-ws-proxy",
    "The database you love, on a serverless platform designed to help you build reliable and…",
    "proxy",
  ],
  [
    "netbird-client",
    "Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and g…",
    "vpn",
  ],
  [
    "newapi",
    "The next-generation LLM gateway and AI asset management system supports multiple langua…",
    "api",
  ],
  [
    "newt-pangolin",
    "Pangolin tunnels your services to the internet so you can access anything from anywhere.",
    "proxy",
  ],
  [
    "next-image-transformation",
    "Drop-in replacement for Vercel's Nextjs image optimization service.",
    "media",
  ],
  [
    "nextcloud",
    "NextCloud is a self-hosted, open-source platform that provides file storage, collaborat…",
    "storage",
  ],
  [
    "nextcloud-with-mariadb",
    "NextCloud is a self-hosted, open-source platform that provides file storage, collaborat…",
    "storage",
  ],
  [
    "nextcloud-with-mysql",
    "NextCloud is a self-hosted, open-source platform that provides file storage, collaborat…",
    "storage",
  ],
  [
    "nextcloud-with-postgres",
    "NextCloud is a self-hosted, open-source platform that provides file storage, collaborat…",
    "storage",
  ],
  [
    "nexus",
    "Open source Universal Repository Manager (x86_64 version, official), default credential…",
    "devtools",
  ],
  [
    "nexus-arm",
    "Open source Universal Repository Manager (ARM version, community edition), default cred…",
    "devtools",
  ],
  [
    "nitropage",
    "Nitropage is an extensible, visual website builder, offering a growing library of versa…",
    "cms",
  ],
  [
    "nitropage-with-postgresql",
    "Nitropage is an extensible, visual website builder, offering a growing library of versa…",
    "cms",
  ],
  [
    "nocobase",
    "NocoBase is the most extensible AI-powered no-code/low-code platform.",
    "development",
  ],
  [
    "nocodb",
    "NocoDB is an open source Airtable alternative. Turns any MySQL, PostgreSQL, SQL Server,…",
    "productivity",
  ],
  ["nodebb", "A next-generation discussion platform.", "messaging"],
  [
    "ntfy",
    "ntfy is a simple HTTP-based pub-sub notification service. It allows you to send notific…",
    "messaging",
  ],
  [
    "observium",
    "Observium is a comprehensive network monitoring platform designed to deliver powerful m…",
    "monitoring",
  ],
  [
    "obsidian",
    "Note-taking app with linking, organizing, and hundreds of plugins - runs in your browse…",
    "productivity",
  ],
  [
    "obsidian-livesync",
    "Self-hosted sync backend for Obsidian LiveSync plugin using CouchDB",
    "storage",
  ],
  [
    "odoo",
    "Odoo is a suite of open-source business apps that cover all your company needs.",
    "productivity",
  ],
  [
    "ollama-with-open-webui",
    "Ollama with Open Web UI integrates AI model deployment with a user-friendly interface.",
    "ai",
  ],
  [
    "once-campfire",
    "Super simple group chat, without a subscription.",
    "messaging",
  ],
  [
    "onedev",
    "Git server with CI/CD, kanban, and packages. Seamless integration. Unparalleled experie…",
    "git",
  ],
  [
    "onetimesecret",
    "Share sensitive information securely with self-destructing links that are only viewable…",
    "security",
  ],
  [
    "open-archiver",
    "A self-hosted, open-source email archiving solution with full-text search capability.",
    "email",
  ],
  [
    "open-webui",
    "User-friendly AI Interface (Supports Ollama, OpenAI API, ...)",
    "ai",
  ],
  [
    "openclaw",
    "AI-powered coding assistant with multi-provider support and browser automation.",
    "ai",
  ],
  [
    "openobserve",
    "Cloud-native observability platform for logs, metrics, traces, RUM, errors and session…",
    "monitoring",
  ],
  [
    "openpanel",
    "Open source alternative to Mixpanel and Plausible for product analytics",
    "analytics",
  ],
  [
    "openwa",
    "Free, open source, self-hosted WhatsApp API gateway with bundled dashboard.",
    "messaging",
  ],
  [
    "openwa-with-postgresql-and-redis",
    "Production OpenWA with PostgreSQL, Redis, and bundled dashboard.",
    "messaging",
  ],
  [
    "opnform",
    "OpnForm is an open-source form builder that lets you create beautiful forms and share t…",
    "productivity",
  ],
  [
    "orangehrm",
    "OrangeHRM open source HR management software.",
    "productivity",
  ],
  ["organizr", "Homelab Services Organizer", "productivity"],
  [
    "overseerr",
    "Overseerr is a request management and media discovery tool built to work with your exis…",
    "media",
  ],
  [
    "owncloud",
    "OwnCloud with Open Web UI integrates file management with a powerful, user-friendly int…",
    "storage",
  ],
  [
    "pairdrop",
    "Pairdrop is a self-hosted file sharing and collaboration platform, offering secure file…",
    "productivity",
  ],
  ["palworld", "Palworld.yaml", "games"],
  [
    "paperless",
    "Paperless-ngx is a community-supported open-source document management system that tran…",
    "productivity",
  ],
  [
    "passbolt",
    "Passbolt Community Edition (CE) API. The JSON API for the open source password manager…",
    "auth",
  ],
  ["paymenter", "Open-Source Billing, Built for Hosting", "finance"],
  ["peertube", "Free, open-source and decentralized video platform.", "media"],
  [
    "penpot",
    "Penpot is the first Open Source design and prototyping platform for product teams.",
    "productivity",
  ],
  [
    "penpot-with-s3",
    "Penpot is the first Open Source design and prototyping platform for product teams.",
    "productivity",
  ],
  [
    "pgadmin",
    "pgAdmin is a web-based database management tool for administering your PostgreSQL datab…",
    "database",
  ],
  [
    "pgbackweb",
    "Effortless PostgreSQL backups with a user-friendly web interface!",
    "devtools",
  ],
  [
    "phpmyadmin",
    "phpMyAdmin is a web-based database management tool for administering your MySQL and Mar…",
    "database",
  ],
  ["pi-hole", "Network-wide Ad Blocking", "proxy"],
  ["plane", "The open source project management tool", "productivity"],
  [
    "plex",
    "Plex organizes video, music and photos from personal media libraries and streams them t…",
    "media",
  ],
  ["plunk", "Plunk, The Open-Source Email Platform for AWS", "email"],
  [
    "pocket-id",
    "A simple and secure OIDC provider with passkey authentication",
    "auth",
  ],
  [
    "pocket-id-with-postgresql",
    "A simple and secure OIDC provider with passkey authentication",
    "auth",
  ],
  [
    "pocketbase",
    "Open Source backend for your next SaaS and Mobile app in 1 file",
    "backend",
  ],
  ["portabase", "Self-hosted database backup & monitoring platform", "other"],
  [
    "portainer",
    "Portainer is a lightweight management UI for Docker",
    "devtools",
  ],
  ["postiz", "Open source social media scheduling tool.", "analytics"],
  [
    "prefect",
    "Prefect is an orchestration and observability platform that empowers developers to buil…",
    "automation",
  ],
  [
    "privatebin",
    "PrivateBin is a minimalist, open source online pastebin where the server has zero knowl…",
    "security",
  ],
  [
    "prowlarr",
    "Prowlarr⁠ is a indexer manager/proxy built on the popular arr .net/reactjs base stack t…",
    "media",
  ],
  [
    "proxyscotch",
    "A simple proxy server created for https://hoppscotch.io - CORS proxy",
    "proxy",
  ],
  [
    "pterodactyl-panel",
    "Pterodactyl is a free, open-source game server management panel",
    "media",
  ],
  [
    "pterodactyl-with-wings",
    "Pterodactyl is a free, open-source game server management panel",
    "media",
  ],
  [
    "pydio-cells",
    "High-performance large file sharing, native no-code automation, and a collaboration-cen…",
    "storage",
  ],
  [
    "qbittorrent",
    "The qBittorrent project aims to provide an open-source software alternative to μTorrent.",
    "media",
  ],
  [
    "qdrant",
    "Qdrant is a vector similarity search engine that provides a production-ready service wi…",
    "database",
  ],
  [
    "rabbitmq",
    "With tens of thousands of users, RabbitMQ is one of the most popular open source messag…",
    "messaging",
  ],
  [
    "radarr",
    "Radarr⁠ - A fork of Sonarr to work with movies à la Couchpotato.",
    "media",
  ],
  [
    "rallly",
    "Rallly is an open-source scheduling and collaboration tool designed to make organizing…",
    "productivity",
  ],
  [
    "reactive-resume",
    "A one-of-a-kind resume builder that keeps your privacy in mind.",
    "productivity",
  ],
  [
    "readeck",
    "Simple web application that lets you save the precious readable content of web pages yo…",
    "productivity",
  ],
  [
    "redis-insight",
    "Redis Insight lets you do both GUI- and CLI-based interactions in a fully-featured desk…",
    "database,observability,developer-tools",
  ],
  [
    "redlib",
    "An alternative private front-end to Reddit, with its origins in Libreddit.",
    "productivity",
  ],
  [
    "redmine",
    "Redmine is a flexible project management web application.",
    "productivity",
  ],
  [
    "rivet-engine",
    "Build and scale stateful workloads with long-lived processes",
    "development",
  ],
  [
    "rocketchat",
    "Self-hosted, secure and highly customizable open-source communication platform for orga…",
    "messaging",
  ],
  ["rybbit", "Open-source, privacy-first web analytics.", "analytics"],
  [
    "ryot",
    "Roll your own tracker! Ryot is a self-hosted platform for tracking various aspects of l…",
    "productivity",
  ],
  [
    "satisfactory",
    "Satisfactory Dedicated Server for hosting your own Satisfactory game sessions.",
    "games",
  ],
  [
    "seafile",
    "Open source cloud storage system for file sync, share and document collaboration",
    "storage",
  ],
  [
    "searxng",
    "SearXNG is a free internet metasearch engine which aggregates results from more than 70…",
    "search",
  ],
  [
    "seaweedfs",
    "SeaweedFS is a simple and highly scalable distributed file system. Compatible with S3,…",
    "storage",
  ],
  ["sequin", "The fastest Postgres change data capture", "analytics"],
  [
    "sessy",
    "Email observability platform for monitoring and analyzing email systems.",
    "monitoring",
  ],
  [
    "sftpgo",
    "SFTPGo is an event-driven SFTP, FTP/S, HTTP/S and WebDAV server.",
    "storage",
  ],
  ["shlink", "The definitive self-hosted URL shortener", "productivity"],
  [
    "signoz",
    "An observability platform native to OpenTelemetry with logs, traces and metrics.",
    "monitoring",
  ],
  [
    "silverbullet",
    "SilverBullet is a tool to develop, organize, and structure your personal knowledge and…",
    "productivity",
  ],
  [
    "siyuan",
    "A privacy-first, self-hosted, fully open source personal knowledge management software,…",
    "documentation",
  ],
  [
    "slash",
    "An open source, self-hosted links shortener and sharing platform.",
    "productivity",
  ],
  [
    "snapdrop",
    "A self-hosted file-sharing service for secure and convenient file transfers, whether on…",
    "productivity",
  ],
  [
    "snipe-it",
    "Snipe-IT is an open-source asset management platform built for IT departments.",
    "productivity",
  ],
  [
    "soju",
    "A user-friendly IRC bouncer with a modern web interface",
    "communication",
  ],
  [
    "soketi",
    "Soketi is your simple, fast, and resilient open-source WebSockets server.",
    "messaging",
  ],
  [
    "soketi-app-manager",
    "Manage soketi websocket server and apps with ease.",
    "devtools",
  ],
  [
    "sonarr",
    "Sonarr⁠ (formerly NZBdrone) is a PVR for usenet and bittorrent users. It can monitor mu…",
    "media",
  ],
  [
    "spacebot",
    "An agentic AI system with specialized processes for thinking, working, and remembering.",
    "ai",
  ],
  [
    "sparkyfitness",
    "SparkyFitness is a comprehensive fitness tracking and management application designed t…",
    "health",
  ],
  ["stalwart", "Modern mail server platform", "Mail"],
  [
    "statusnook",
    "Effortlessly deploy a status page and start monitoring endpoints in minutes",
    "monitoring",
  ],
  [
    "stirling-pdf",
    "Stirling is a powerful web based PDF manipulation tool",
    "productivity",
  ],
  [
    "strapi",
    "Open-source headless CMS to build powerful APIs with built-in content management.",
    "backend",
  ],
  ["supabase", "The open source Firebase alternative.", "backend"],
  [
    "superset-with-postgresql",
    "Modern data exploration and visualization platform (unofficial community docker image)",
    "analytics",
  ],
  [
    "supertokens-with-mysql",
    "An open-source authentication solution that simplifies the implementation of secure use…",
    "auth",
  ],
  [
    "supertokens-with-postgresql",
    "An open-source authentication solution that simplifies the implementation of secure use…",
    "auth",
  ],
  ["sure", "An all-in-one personal finance platform.", "finance"],
  [
    "swetrix",
    "Privacy-friendly and cookieless European web analytics alternative to Google Analytics.",
    "analytics",
  ],
  [
    "syncthing",
    "Syncthing synchronizes files between two or more computers in real time.",
    "storage",
  ],
  [
    "tailscale-client",
    "Tailscale securely connects your devices over the internet using WireGuard.",
    "networking",
  ],
  [
    "teable",
    "Teable is a powerful visual interface built on relational databases (PostgreSQL).",
    "productivity",
  ],
  [
    "termix",
    "All-in-One SSH & Remote Desktop management app.",
    "developer-tools",
  ],
  ["terraria-server", "Docker multi-arch Image for Terraria Server.", "games"],
  [
    "tolgee",
    "Tolgee is a localization management platform for developers and translators.",
    "productivity",
  ],
  [
    "traccar",
    "Traccar is a free and open source modern GPS tracking system.",
    "monitoring",
  ],
  [
    "trailbase",
    "A blazingly fast Rust/SQLite/Wasmtime app server with type-safe APIs",
    "backend",
  ],
  ["transmission", "Fast, easy, and free BitTorrent client.", "media"],
  [
    "trigger",
    "The open source background jobs platform for developers",
    "automation",
  ],
  [
    "triliumnext",
    "Build your personal knowledge base with TriliumNext Notes.",
    "productivity",
  ],
  [
    "twenty",
    "Twenty is a CRM designed to fit your unique business needs.",
    "productivity",
  ],
  [
    "typesense",
    "Cutting-edge, in-memory search engine for mere mortals. Knowledge of rocket science opt…",
    "search",
  ],
  [
    "umami",
    "Umami is web analytics platform which provides insights into visitor behavior without c…",
    "analytics",
  ],
  [
    "unleash-with-postgresql",
    "Open source feature flag management for enterprises.",
    "devtools",
  ],
  [
    "unleash-without-database",
    "Open source feature flag management for enterprises.",
    "devtools",
  ],
  [
    "unstructured",
    "Unstructured provides a platform and tools to ingest and process unstructured documents…",
    "ai",
  ],
  [
    "uptime-kuma",
    "Uptime Kuma is a monitoring tool for tracking the status and performance of your applic…",
    "monitoring",
  ],
  [
    "uptime-kuma-with-mariadb",
    "Uptime Kuma is a monitoring tool for tracking the status and performance of your applic…",
    "monitoring",
  ],
  [
    "uptime-kuma-with-mysql",
    "Uptime Kuma is a monitoring tool for tracking the status and performance of your applic…",
    "monitoring",
  ],
  [
    "usesend",
    "Usesend is an open-source alternative to Resend, Sendgrid, Mailgun and Postmark etc.",
    "email",
  ],
  [
    "vault",
    "HashiCorp Vault securely stores and controls access to secrets.",
    "security",
  ],
  [
    "vaultwarden",
    "Vaultwarden is a password manager that allows you to securely store and manage your pas…",
    "auth",
  ],
  [
    "vert",
    "The next-generation file converter. Open source, fully local and free forever.",
    "devtools",
  ],
  [
    "vikunja",
    "The open-source, self-hostable to-do app. Organize everything, on all platforms.",
    "productivity",
  ],
  [
    "vikunja-with-postgresql",
    "The open-source, self-hostable to-do app. Organize everything, on all platforms.",
    "productivity",
  ],
  [
    "vvveb",
    "Powerful and easy to use cms to build websites, blogs or ecommerce stores.",
    "cms",
  ],
  [
    "vvveb-with-mariadb",
    "Powerful and easy to use cms to build websites, blogs or ecommerce stores.",
    "cms",
  ],
  [
    "vvveb-with-mysql",
    "Powerful and easy to use cms to build websites, blogs or ecommerce stores.",
    "cms",
  ],
  [
    "wakapi",
    "A minimalist, self-hosted WakaTime-compatible backend for coding statistics",
    "analytics",
  ],
  [
    "weaviate",
    "Weaviate is an open-source vector database that stores both objects and vectors, allowi…",
    "ai",
  ],
  [
    "web-check",
    "All-in-one OSINT tool for analysing any website",
    "monitoring",
  ],
  [
    "weblate",
    "Weblate is a libre software web-based continuous localization system.",
    "productivity",
  ],
  [
    "whoogle",
    "Whoogle is a self-hosted, privacy-focused search engine front-end for accessing Google…",
    "search",
  ],
  [
    "wikijs",
    "The most powerful and extensible open source Wiki software.",
    "cms",
  ],
  [
    "windmill",
    "Windmill is a developer platform to build production-grade multi-steps automations and…",
    "automation",
  ],
  [
    "wings",
    "The server control plane for Pterodactyl Panel. Written from the ground-up with securit…",
    "devtools",
  ],
  [
    "wireguard-easy",
    "The easiest way to run WireGuard VPN + Web-based Admin UI.",
    "vpn",
  ],
  [
    "wordpress-with-mariadb",
    "WordPress is open source software you can use to create a beautiful website, blog, or app.",
    "cms",
  ],
  [
    "wordpress-with-mysql",
    "WordPress is open source software you can use to create a beautiful website, blog, or app.",
    "cms",
  ],
  [
    "wordpress-without-database",
    "WordPress is open source software you can use to create a beautiful website, blog, or app.",
    "cms",
  ],
  [
    "yamtrack",
    "Yamtrack is a self hosted media tracker for movies, tv shows, anime, manga, video games…",
    "productivity",
  ],
  [
    "yamtrack-with-postgresql",
    "Yamtrack is a self hosted media tracker for movies, tv shows, anime, manga, video games…",
    "productivity",
  ],
  [
    "zero",
    "Query-driven sync engine for TypeScript apps backed by Postgres.",
    "backend",
  ],
  [
    "zipline",
    "A ShareX/file upload server that is easy to use, packed with features, and with an easy…",
    "media",
  ],
];
